/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as AppShellRouteImport } from './routes/_app/_shell'
import { Route as AppExportRouteImport } from './routes/_app/export'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AccountSettingsRouteImport } from './routes/account.settings'
import { Route as AuthSignInRouteImport } from './routes/auth.sign-in'
import { Route as AuthSignUpRouteImport } from './routes/auth.sign-up'
import { Route as AppShellExploreRouteImport } from './routes/_app/_shell/explore'
import { Route as AppShellHomeRouteImport } from './routes/_app/_shell/home'
import { Route as AppShellLibraryRouteImport } from './routes/_app/_shell/library'
import { Route as AppShellPatternsRouteImport } from './routes/_app/_shell/patterns'
import { Route as AppShellPlanRouteImport } from './routes/_app/_shell/plan'
import { Route as AppShellProfileRouteImport } from './routes/_app/_shell/profile'
import { Route as AppShellTodayRouteImport } from './routes/_app/_shell/today'
import { Route as AppChunksIdRouteImport } from './routes/_app/chunks.$id'
import { Route as AppChunksNewRouteImport } from './routes/_app/chunks.new'
import { Route as AppDialoguesIdRouteImport } from './routes/_app/dialogues.$id'
import { Route as AppDrillsPatternIdRouteImport } from './routes/_app/drills.$patternId'
import { Route as AppPracticeSessionRouteImport } from './routes/_app/practice.session'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as AppShellLearnIndexRouteImport } from './routes/_app/_shell/learn.index'
import { Route as AppShellPracticeIndexRouteImport } from './routes/_app/_shell/practice.index'
import { Route as AppShellPracticeDoneRouteImport } from './routes/_app/_shell/practice.done'
import { Route as AppShellPracticeSpeakRouteImport } from './routes/_app/_shell/practice.speak'
import { Route as AppShellSavedIndexRouteImport } from './routes/_app/_shell/saved.index'
import { Route as AppShellSavedIdRouteImport } from './routes/_app/_shell/saved.$id'
import { Route as AppShellSituationsIndexRouteImport } from './routes/_app/_shell/situations.index'
import { Route as AppSituationsIdIndexRouteImport } from './routes/_app/situations.$id.index'
import { Route as AppSituationsIdBuildRouteImport } from './routes/_app/situations.$id.build'
import { Route as AppShellLearnTopicIndexRouteImport } from './routes/_app/_shell/learn.$topic.index'
import { Route as AppShellLearnTopicStepRouteImport } from './routes/_app/_shell/learn.$topic.$step'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const AppShellRoute = AppShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => AppRoute,
} as any)
const AppExportRoute = AppExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/account/settings',
  path: '/account/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AppShellExploreRoute = AppShellExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppShellRoute,
} as any)
const AppShellHomeRoute = AppShellHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppShellRoute,
} as any)
const AppShellLibraryRoute = AppShellLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppShellRoute,
} as any)
const AppShellPatternsRoute = AppShellPatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => AppShellRoute,
} as any)
const AppShellPlanRoute = AppShellPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppShellRoute,
} as any)
const AppShellProfileRoute = AppShellProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppShellRoute,
} as any)
const AppShellTodayRoute = AppShellTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppShellRoute,
} as any)
const AppChunksIdRoute = AppChunksIdRouteImport.update({
  id: '/chunks/$id',
  path: '/chunks/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppChunksNewRoute = AppChunksNewRouteImport.update({
  id: '/chunks/new',
  path: '/chunks/new',
  getParentRoute: () => AppRoute,
} as any)
const AppDialoguesIdRoute = AppDialoguesIdRouteImport.update({
  id: '/dialogues/$id',
  path: '/dialogues/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDrillsPatternIdRoute = AppDrillsPatternIdRouteImport.update({
  id: '/drills/$patternId',
  path: '/drills/$patternId',
  getParentRoute: () => AppRoute,
} as any)
const AppPracticeSessionRoute = AppPracticeSessionRouteImport.update({
  id: '/practice/session',
  path: '/practice/session',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppShellLearnIndexRoute = AppShellLearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => AppShellRoute,
} as any)
const AppShellPracticeIndexRoute = AppShellPracticeIndexRouteImport.update({
  id: '/practice/',
  path: '/practice/',
  getParentRoute: () => AppShellRoute,
} as any)
const AppShellPracticeDoneRoute = AppShellPracticeDoneRouteImport.update({
  id: '/practice/done',
  path: '/practice/done',
  getParentRoute: () => AppShellRoute,
} as any)
const AppShellPracticeSpeakRoute = AppShellPracticeSpeakRouteImport.update({
  id: '/practice/speak',
  path: '/practice/speak',
  getParentRoute: () => AppShellRoute,
} as any)
const AppShellSavedIndexRoute = AppShellSavedIndexRouteImport.update({
  id: '/saved/',
  path: '/saved/',
  getParentRoute: () => AppShellRoute,
} as any)
const AppShellSavedIdRoute = AppShellSavedIdRouteImport.update({
  id: '/saved/$id',
  path: '/saved/$id',
  getParentRoute: () => AppShellRoute,
} as any)
const AppShellSituationsIndexRoute = AppShellSituationsIndexRouteImport.update({
  id: '/situations/',
  path: '/situations/',
  getParentRoute: () => AppShellRoute,
} as any)
const AppSituationsIdIndexRoute = AppSituationsIdIndexRouteImport.update({
  id: '/situations/$id/',
  path: '/situations/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppSituationsIdBuildRoute = AppSituationsIdBuildRouteImport.update({
  id: '/situations/$id/build',
  path: '/situations/$id/build',
  getParentRoute: () => AppRoute,
} as any)
const AppShellLearnTopicIndexRoute = AppShellLearnTopicIndexRouteImport.update({
  id: '/learn/$topic/',
  path: '/learn/$topic/',
  getParentRoute: () => AppShellRoute,
} as any)
const AppShellLearnTopicStepRoute = AppShellLearnTopicStepRouteImport.update({
  id: '/learn/$topic/$step',
  path: '/learn/$topic/$step',
  getParentRoute: () => AppShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/monitoring': typeof MonitoringRoute
  '/export': typeof AppExportRoute
  '/onboarding': typeof AppOnboardingRoute
  '/settings': typeof AppSettingsRoute
  '/account/settings': typeof AccountSettingsRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/explore': typeof AppShellExploreRoute
  '/home': typeof AppShellHomeRoute
  '/library': typeof AppShellLibraryRoute
  '/patterns': typeof AppShellPatternsRoute
  '/plan': typeof AppShellPlanRoute
  '/profile': typeof AppShellProfileRoute
  '/today': typeof AppShellTodayRoute
  '/chunks/$id': typeof AppChunksIdRoute
  '/chunks/new': typeof AppChunksNewRoute
  '/dialogues/$id': typeof AppDialoguesIdRoute
  '/drills/$patternId': typeof AppDrillsPatternIdRoute
  '/practice/session': typeof AppPracticeSessionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/practice/done': typeof AppShellPracticeDoneRoute
  '/practice/speak': typeof AppShellPracticeSpeakRoute
  '/saved/$id': typeof AppShellSavedIdRoute
  '/situations/$id/build': typeof AppSituationsIdBuildRoute
  '/learn/': typeof AppShellLearnIndexRoute
  '/practice/': typeof AppShellPracticeIndexRoute
  '/saved/': typeof AppShellSavedIndexRoute
  '/situations/': typeof AppShellSituationsIndexRoute
  '/situations/$id/': typeof AppSituationsIdIndexRoute
  '/learn/$topic/$step': typeof AppShellLearnTopicStepRoute
  '/learn/$topic/': typeof AppShellLearnTopicIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/monitoring': typeof MonitoringRoute
  '/export': typeof AppExportRoute
  '/onboarding': typeof AppOnboardingRoute
  '/settings': typeof AppSettingsRoute
  '/account/settings': typeof AccountSettingsRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/explore': typeof AppShellExploreRoute
  '/home': typeof AppShellHomeRoute
  '/library': typeof AppShellLibraryRoute
  '/patterns': typeof AppShellPatternsRoute
  '/plan': typeof AppShellPlanRoute
  '/profile': typeof AppShellProfileRoute
  '/today': typeof AppShellTodayRoute
  '/chunks/$id': typeof AppChunksIdRoute
  '/chunks/new': typeof AppChunksNewRoute
  '/dialogues/$id': typeof AppDialoguesIdRoute
  '/drills/$patternId': typeof AppDrillsPatternIdRoute
  '/practice/session': typeof AppPracticeSessionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/practice/done': typeof AppShellPracticeDoneRoute
  '/practice/speak': typeof AppShellPracticeSpeakRoute
  '/saved/$id': typeof AppShellSavedIdRoute
  '/situations/$id/build': typeof AppSituationsIdBuildRoute
  '/learn': typeof AppShellLearnIndexRoute
  '/practice': typeof AppShellPracticeIndexRoute
  '/saved': typeof AppShellSavedIndexRoute
  '/situations': typeof AppShellSituationsIndexRoute
  '/situations/$id': typeof AppSituationsIdIndexRoute
  '/learn/$topic/$step': typeof AppShellLearnTopicStepRoute
  '/learn/$topic': typeof AppShellLearnTopicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/monitoring': typeof MonitoringRoute
  '/_app/_shell': typeof AppShellRouteWithChildren
  '/_app/export': typeof AppExportRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/settings': typeof AppSettingsRoute
  '/account/settings': typeof AccountSettingsRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/_app/_shell/explore': typeof AppShellExploreRoute
  '/_app/_shell/home': typeof AppShellHomeRoute
  '/_app/_shell/library': typeof AppShellLibraryRoute
  '/_app/_shell/patterns': typeof AppShellPatternsRoute
  '/_app/_shell/plan': typeof AppShellPlanRoute
  '/_app/_shell/profile': typeof AppShellProfileRoute
  '/_app/_shell/today': typeof AppShellTodayRoute
  '/_app/chunks/$id': typeof AppChunksIdRoute
  '/_app/chunks/new': typeof AppChunksNewRoute
  '/_app/dialogues/$id': typeof AppDialoguesIdRoute
  '/_app/drills/$patternId': typeof AppDrillsPatternIdRoute
  '/_app/practice/session': typeof AppPracticeSessionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/_shell/practice/done': typeof AppShellPracticeDoneRoute
  '/_app/_shell/practice/speak': typeof AppShellPracticeSpeakRoute
  '/_app/_shell/saved/$id': typeof AppShellSavedIdRoute
  '/_app/situations/$id/build': typeof AppSituationsIdBuildRoute
  '/_app/_shell/learn/': typeof AppShellLearnIndexRoute
  '/_app/_shell/practice/': typeof AppShellPracticeIndexRoute
  '/_app/_shell/saved/': typeof AppShellSavedIndexRoute
  '/_app/_shell/situations/': typeof AppShellSituationsIndexRoute
  '/_app/situations/$id/': typeof AppSituationsIdIndexRoute
  '/_app/_shell/learn/$topic/$step': typeof AppShellLearnTopicStepRoute
  '/_app/_shell/learn/$topic/': typeof AppShellLearnTopicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/monitoring'
    | '/export'
    | '/onboarding'
    | '/settings'
    | '/account/settings'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/explore'
    | '/home'
    | '/library'
    | '/patterns'
    | '/plan'
    | '/profile'
    | '/today'
    | '/chunks/$id'
    | '/chunks/new'
    | '/dialogues/$id'
    | '/drills/$patternId'
    | '/practice/session'
    | '/api/auth/$'
    | '/practice/done'
    | '/practice/speak'
    | '/saved/$id'
    | '/situations/$id/build'
    | '/learn/'
    | '/practice/'
    | '/saved/'
    | '/situations/'
    | '/situations/$id/'
    | '/learn/$topic/$step'
    | '/learn/$topic/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/monitoring'
    | '/export'
    | '/onboarding'
    | '/settings'
    | '/account/settings'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/explore'
    | '/home'
    | '/library'
    | '/patterns'
    | '/plan'
    | '/profile'
    | '/today'
    | '/chunks/$id'
    | '/chunks/new'
    | '/dialogues/$id'
    | '/drills/$patternId'
    | '/practice/session'
    | '/api/auth/$'
    | '/practice/done'
    | '/practice/speak'
    | '/saved/$id'
    | '/situations/$id/build'
    | '/learn'
    | '/practice'
    | '/saved'
    | '/situations'
    | '/situations/$id'
    | '/learn/$topic/$step'
    | '/learn/$topic'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/monitoring'
    | '/_app/_shell'
    | '/_app/export'
    | '/_app/onboarding'
    | '/_app/settings'
    | '/account/settings'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/_app/_shell/explore'
    | '/_app/_shell/home'
    | '/_app/_shell/library'
    | '/_app/_shell/patterns'
    | '/_app/_shell/plan'
    | '/_app/_shell/profile'
    | '/_app/_shell/today'
    | '/_app/chunks/$id'
    | '/_app/chunks/new'
    | '/_app/dialogues/$id'
    | '/_app/drills/$patternId'
    | '/_app/practice/session'
    | '/api/auth/$'
    | '/_app/_shell/practice/done'
    | '/_app/_shell/practice/speak'
    | '/_app/_shell/saved/$id'
    | '/_app/situations/$id/build'
    | '/_app/_shell/learn/'
    | '/_app/_shell/practice/'
    | '/_app/_shell/saved/'
    | '/_app/_shell/situations/'
    | '/_app/situations/$id/'
    | '/_app/_shell/learn/$topic/$step'
    | '/_app/_shell/learn/$topic/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  MonitoringRoute: typeof MonitoringRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_shell': {
      id: '/_app/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppShellRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/export': {
      id: '/_app/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AppExportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_shell/explore': {
      id: '/_app/_shell/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AppShellExploreRouteImport
      parentRoute: typeof AppShellRoute
    }
    '/_app/_shell/home': {
      id: '/_app/_shell/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppShellHomeRouteImport
      parentRoute: typeof AppShellRoute
    }
    '/_app/_shell/library': {
      id: '/_app/_shell/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppShellLibraryRouteImport
      parentRoute: typeof AppShellRoute
    }
    '/_app/_shell/patterns': {
      id: '/_app/_shell/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof AppShellPatternsRouteImport
      parentRoute: typeof AppShellRoute
    }
    '/_app/_shell/plan': {
      id: '/_app/_shell/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AppShellPlanRouteImport
      parentRoute: typeof AppShellRoute
    }
    '/_app/_shell/profile': {
      id: '/_app/_shell/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppShellProfileRouteImport
      parentRoute: typeof AppShellRoute
    }
    '/_app/_shell/today': {
      id: '/_app/_shell/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AppShellTodayRouteImport
      parentRoute: typeof AppShellRoute
    }
    '/_app/chunks/$id': {
      id: '/_app/chunks/$id'
      path: '/chunks/$id'
      fullPath: '/chunks/$id'
      preLoaderRoute: typeof AppChunksIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chunks/new': {
      id: '/_app/chunks/new'
      path: '/chunks/new'
      fullPath: '/chunks/new'
      preLoaderRoute: typeof AppChunksNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dialogues/$id': {
      id: '/_app/dialogues/$id'
      path: '/dialogues/$id'
      fullPath: '/dialogues/$id'
      preLoaderRoute: typeof AppDialoguesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/drills/$patternId': {
      id: '/_app/drills/$patternId'
      path: '/drills/$patternId'
      fullPath: '/drills/$patternId'
      preLoaderRoute: typeof AppDrillsPatternIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/practice/session': {
      id: '/_app/practice/session'
      path: '/practice/session'
      fullPath: '/practice/session'
      preLoaderRoute: typeof AppPracticeSessionRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_shell/learn/': {
      id: '/_app/_shell/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof AppShellLearnIndexRouteImport
      parentRoute: typeof AppShellRoute
    }
    '/_app/_shell/practice/': {
      id: '/_app/_shell/practice/'
      path: '/practice'
      fullPath: '/practice/'
      preLoaderRoute: typeof AppShellPracticeIndexRouteImport
      parentRoute: typeof AppShellRoute
    }
    '/_app/_shell/practice/done': {
      id: '/_app/_shell/practice/done'
      path: '/practice/done'
      fullPath: '/practice/done'
      preLoaderRoute: typeof AppShellPracticeDoneRouteImport
      parentRoute: typeof AppShellRoute
    }
    '/_app/_shell/practice/speak': {
      id: '/_app/_shell/practice/speak'
      path: '/practice/speak'
      fullPath: '/practice/speak'
      preLoaderRoute: typeof AppShellPracticeSpeakRouteImport
      parentRoute: typeof AppShellRoute
    }
    '/_app/_shell/saved/': {
      id: '/_app/_shell/saved/'
      path: '/saved'
      fullPath: '/saved/'
      preLoaderRoute: typeof AppShellSavedIndexRouteImport
      parentRoute: typeof AppShellRoute
    }
    '/_app/_shell/saved/$id': {
      id: '/_app/_shell/saved/$id'
      path: '/saved/$id'
      fullPath: '/saved/$id'
      preLoaderRoute: typeof AppShellSavedIdRouteImport
      parentRoute: typeof AppShellRoute
    }
    '/_app/_shell/situations/': {
      id: '/_app/_shell/situations/'
      path: '/situations'
      fullPath: '/situations/'
      preLoaderRoute: typeof AppShellSituationsIndexRouteImport
      parentRoute: typeof AppShellRoute
    }
    '/_app/situations/$id/': {
      id: '/_app/situations/$id/'
      path: '/situations/$id'
      fullPath: '/situations/$id/'
      preLoaderRoute: typeof AppSituationsIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/situations/$id/build': {
      id: '/_app/situations/$id/build'
      path: '/situations/$id/build'
      fullPath: '/situations/$id/build'
      preLoaderRoute: typeof AppSituationsIdBuildRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_shell/learn/$topic/': {
      id: '/_app/_shell/learn/$topic/'
      path: '/learn/$topic'
      fullPath: '/learn/$topic/'
      preLoaderRoute: typeof AppShellLearnTopicIndexRouteImport
      parentRoute: typeof AppShellRoute
    }
    '/_app/_shell/learn/$topic/$step': {
      id: '/_app/_shell/learn/$topic/$step'
      path: '/learn/$topic/$step'
      fullPath: '/learn/$topic/$step'
      preLoaderRoute: typeof AppShellLearnTopicStepRouteImport
      parentRoute: typeof AppShellRoute
    }
  }
}

interface AppShellRouteChildren {
  AppShellExploreRoute: typeof AppShellExploreRoute
  AppShellHomeRoute: typeof AppShellHomeRoute
  AppShellLibraryRoute: typeof AppShellLibraryRoute
  AppShellPatternsRoute: typeof AppShellPatternsRoute
  AppShellPlanRoute: typeof AppShellPlanRoute
  AppShellProfileRoute: typeof AppShellProfileRoute
  AppShellTodayRoute: typeof AppShellTodayRoute
  AppShellPracticeDoneRoute: typeof AppShellPracticeDoneRoute
  AppShellPracticeSpeakRoute: typeof AppShellPracticeSpeakRoute
  AppShellSavedIdRoute: typeof AppShellSavedIdRoute
  AppShellLearnIndexRoute: typeof AppShellLearnIndexRoute
  AppShellPracticeIndexRoute: typeof AppShellPracticeIndexRoute
  AppShellSavedIndexRoute: typeof AppShellSavedIndexRoute
  AppShellSituationsIndexRoute: typeof AppShellSituationsIndexRoute
  AppShellLearnTopicStepRoute: typeof AppShellLearnTopicStepRoute
  AppShellLearnTopicIndexRoute: typeof AppShellLearnTopicIndexRoute
}

const AppShellRouteChildren: AppShellRouteChildren = {
  AppShellExploreRoute: AppShellExploreRoute,
  AppShellHomeRoute: AppShellHomeRoute,
  AppShellLibraryRoute: AppShellLibraryRoute,
  AppShellPatternsRoute: AppShellPatternsRoute,
  AppShellPlanRoute: AppShellPlanRoute,
  AppShellProfileRoute: AppShellProfileRoute,
  AppShellTodayRoute: AppShellTodayRoute,
  AppShellPracticeDoneRoute: AppShellPracticeDoneRoute,
  AppShellPracticeSpeakRoute: AppShellPracticeSpeakRoute,
  AppShellSavedIdRoute: AppShellSavedIdRoute,
  AppShellLearnIndexRoute: AppShellLearnIndexRoute,
  AppShellPracticeIndexRoute: AppShellPracticeIndexRoute,
  AppShellSavedIndexRoute: AppShellSavedIndexRoute,
  AppShellSituationsIndexRoute: AppShellSituationsIndexRoute,
  AppShellLearnTopicStepRoute: AppShellLearnTopicStepRoute,
  AppShellLearnTopicIndexRoute: AppShellLearnTopicIndexRoute,
}

const AppShellRouteWithChildren = AppShellRoute._addFileChildren(
  AppShellRouteChildren,
)

interface AppRouteChildren {
  AppShellRoute: typeof AppShellRouteWithChildren
  AppExportRoute: typeof AppExportRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppChunksIdRoute: typeof AppChunksIdRoute
  AppChunksNewRoute: typeof AppChunksNewRoute
  AppDialoguesIdRoute: typeof AppDialoguesIdRoute
  AppDrillsPatternIdRoute: typeof AppDrillsPatternIdRoute
  AppPracticeSessionRoute: typeof AppPracticeSessionRoute
  AppSituationsIdBuildRoute: typeof AppSituationsIdBuildRoute
  AppSituationsIdIndexRoute: typeof AppSituationsIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppShellRoute: AppShellRouteWithChildren,
  AppExportRoute: AppExportRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppChunksIdRoute: AppChunksIdRoute,
  AppChunksNewRoute: AppChunksNewRoute,
  AppDialoguesIdRoute: AppDialoguesIdRoute,
  AppDrillsPatternIdRoute: AppDrillsPatternIdRoute,
  AppPracticeSessionRoute: AppPracticeSessionRoute,
  AppSituationsIdBuildRoute: AppSituationsIdBuildRoute,
  AppSituationsIdIndexRoute: AppSituationsIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  MonitoringRoute: MonitoringRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
